services:
    Rector\Rector\CodeQuality\InArrayAndArrayKeysToArrayKeyExistsRector: ~
    Rector\Rector\CodeQuality\UnnecessaryTernaryExpressionRector: ~
    Rector\Rector\CodeQuality\ForeachToInArrayRector: ~
